### ISSUE TITLE
[Thread] For v2.0.1

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#1]
idk how to tell u this so i just simply create a ticket, LethalCompanyVariables UI is better than before (actually im not using that mod bc the UI is not really useful), thx for ur mod, keep it up!
\* after 3 weeks i install this mod, and im shock a while for the mod UI, yea if this UI change are more sooner, i guess i won't change so much things in my modpack
\* if u can, add a support to let user create their own profile to save configuration, and can load the config via LethalCompanyVariables UI

**Comment by CoolLKKPS** [comment]
add a feedback here, prevent u don't know the change

**Comment by TheAnsuz** [comment]
Hello CoolLK. Thank you for the feedback.

About the idea of being able to save profile configurations. Right now the mod will save your settings only for the current profile, you can however export and import configurations manually with the "copy" and "paste" buttons. 

I will add a method to export and import configurations among the profile in a future release.

Thank you!

**Comment by TheAnsuz** [comment]
I'll keep the issue open until an update with the capability to import/export the configuration with the profile is added

**Comment by TheAnsuz** [comment]
The next release will include a panel to setup configuration presets that will be shared with your profile code/file and can be imported/exported.

![image of the presets panel](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/84103225/6d260813-9726-4109-8c15-3251b5f5bdc2)

I'will mark the issue as closed but feel free to reopen for any related information.

**Comment by CoolLKKPS** [comment]
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/96377775/138a337c-4321-44eb-8e2a-e4fce7c127c7)

**Comment by CoolLKKPS** [comment]
so here's the logs, pretty sure that's bc i disabled levelloader in the game

[06:39:17.6060795] [Info   :   BepInEx] Loading [Configurable Company Variables 2.0.0]
[06:39:17.9126683] [Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly Lethal_Company_Variables, Version=1.9.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <787acc3c9a4c471ba7d971300105af24>:IL_0000
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:IL_000D
System.TypeLoadException: Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
[06:39:18.1387508] [Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
LCV.Utils.InitiateAttribute.InitiateAll () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/Utils/InitiateAttribute.cs:33)
LCV.LCVPlugin.Awake () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/LCVPlugin.cs:36)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[06:39:18.1387508] [Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
LCV.Utils.InitiateAttribute.InitiateAll () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/Utils/InitiateAttribute.cs:33)
LCV.LCVPlugin.Awake () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/LCVPlugin.cs:36)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by TheAnsuz** [comment]
Hey @CoolLKKPS 

Sorry to not answer sooner, this error has been addressed recently. Make sure to have the latest version of Configurable Company and everything should be fine!

If the issue persist, mention me or open a new issue so I can fix it faster.
Thanks in advance!

**Comment by CoolLKKPS** [comment]
[LogOutput.log](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/files/14905121/LogOutput.log)
@TheAnsuz v50

**Comment by CoolLKKPS** [comment]
im still working on my v50 modpack and my timezone are actually UTC+8, so maybe test this mod tomorrow

**Comment by TheAnsuz** [comment]
Hey @CoolLKKPS 

It is known that v50 has an issue when loading enemy powers, this should not affect other configurations and might only throw that error but keep the mod working with the other configurations.

I however see that LCV does not report to be completly loaded to which I will look and see what is the reason.

Do you see the menu and other configurations or does the mod completly break?

Thanks for the report

**Comment by CoolLKKPS** [comment]
ok and i prefer to play v50 now since playing v49 are real boring for me now, anyway will try to keep tracking the issues if issues happen

**Comment by TheAnsuz** [comment]
Alright, thanks @CoolLKKPS 

Anyway the same day v50 releases as non-beta LCV will be updated to fully support the version (As I mentioned, right now I won't update as most people still play v49 and an update would break this version)
