### ISSUE TITLE
[FEATURE] Property changed indicator.

### ISSUE THREAD

**Issue by AfterRebelion** [TheAnsuz/Lethal-Company-Configurable-Company-API#10]
## **Feature**
Visual indicator when a setting is not in it's default value.

## **Reason**
Makes it easier to identify when you modified a value.

## **Implementation**
I'v seen this implemented in other games, having the "Reset Config" button being grayed out, when that config is already in it's default value. Others have the name of the config **bold**, when it's set to a non-standard value.

**Comment by TheAnsuz** [comment]
Hello @AfterRebelion 

Your suggestions makes a lot of sense to be implemented.

I will work on it to be added in a future release.

Thank you for the suggestion!

**Comment by TheAnsuz** [comment]
Hey @AfterRebelion

The `3.3.0` has been released and it covers this feature. Modified but not saved configurations now will appear in *italic* and those configurations whose value does not match the default one will appear in **bold**.

I will mark the feature as completed. Feel free to open it back if the change does not cover what you originally thougth.

Thanks in advance!
