### ISSUE TITLE
Global enemy type probabiliaties?

### ISSUE THREAD

**Issue by Gragyriss** [TheAnsuz/Lethal-Company-Configurable-Company-API#11]
## **Question**
I remember that before some of the current versions it was possible to modify individual enemy type spawns globally for all maps, but cant find it anymore, was this option removed, replaced, or moved?

**Comment by TheAnsuz** [comment]
Hello @Gragyriss 

This option was replaced by the individual settings for each moon. Still, don't worry as it will be added back in the next release.

**Comment by Gragyriss** [comment]
Oh, thanks, thats a huge relief, I experiment with balance a lot, and that feature made it easier, glad to hear your so on top of it.

**Comment by TheAnsuz** [comment]
Yea no worries, that will be added as part of 2.1.0 (Im waiting for the v50 release to upload it as it breaks v49 compatibility sadly).

If you have any other suggestion, feel free to notify about it in an issue, the discord or the requests excel.

Thank you!
