### ISSUE TITLE
[BUG] when i click on anything it dosent work it just leaves me on enemies

### ISSUE THREAD

**Issue by chonkstervr** [TheAnsuz/Lethal-Company-Configurable-Company-API#12]
## **Describe the bug**
What happened that made you think something does not work as intended. A short description with something like *The menu does not open regardless of how many times I click*.

## **How to reproduce the issue**
Try to explain what you did to reproduce the issue. If you down know what you did ir is unclear, leave it blank. For example *click host, go back and then click again*

## **Mods and profile**
It's very important that you write the version of the game and the version of Configurable Company or any related mods to the issue. Use the following line:
- Game version: v49
- Configurable company: v3.3.0

Profile code: my_profile_code

## **Extra information**
Anything else you want to add. If you have console logs, any error or screenshot, this is the ideal place, otehrwise, you can just leave it empty.

**Comment by chonkstervr** [comment]
when i click on anything it does nothing im just stuck on the screen for enemy power ect so i was wondering if you could help me in any way

**Comment by chonkstervr** [comment]
if you need a vid of the probl

Uploading Lethal Company 2024-04-08 20-47-55.mp4…

**Comment by TheAnsuz** [comment]
Hello @chonkstervr 

Does this bug happen in v50 or v49.
LCV does only partially support v50 (Once it's released it will be fully supported) However the only difference is that in v50 some features are disabled, for example custom enemy power.

If the issue is happening in v49, I would suggest to send the profile code so I can take a look into the issue.

Thanks in advance.

**Comment by chonkstervr** [comment]
I think it’s  V49

**Comment by chonkstervr** [comment]
I will send the mod pack code soon

**Comment by chonkstervr** [comment]
018ec547-8d2b-1d3a-7323-035867f69481

**Comment by chonkstervr** [comment]
yoooo you fixed it thank you so much

**Comment by TheAnsuz** [comment]
Thats good news.

I will mark the issue as closed, thanks for the report @chonkstervr !
