### ISSUE TITLE
[QUESTION] why cant i click on the other setting such as gameplay or extra

### ISSUE THREAD

**Issue by Zokza** [TheAnsuz/Lethal-Company-Configurable-Company-API#13]
## **Question**
Ask your question. 
You can add as much information as you want, for example a screenshot to help me understand what you ask.

**Comment by TheAnsuz** [comment]
Hey @Zokza 

I might need more information about your question, as I understand, you can't click on the section named "Extra" or "Gameplay", does this happen in v50 or v49 of the game?
