### ISSUE TITLE
[FEATURE] Add a sub-option in planets option, to custom min/max scrap value

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#16]
## **Feature**
Add a sub-option in planets option, to custom `min/max scrap value` (each planets) / `min/max scrap value multiplier` (global)

## **Reason**
so recently i checked "infected company" and other mods similar like pvp, and i found out the difficulty is not really good enough, and i know i can use "hullbreaker company" mod to custom total min/max scrap value and can that mod can work with vanilla, but i more like to see this feature in this mod

**Comment by TheAnsuz** [comment]
Hello @CoolLKKPS 

That option was discarded because the game seemed to not use those settings, they are only used **for debug purposes**, I will check if this has changed and they do affect the game but Im pretty sure these settings are not used.

Could you confirm you note a difference in the scrap value when changing it within hullbreaker company?

Thanks in advance, I will notify you from any advance.

**Comment by CoolLKKPS** [comment]
i will let u know when i finished test hullbreaker

**Comment by TheAnsuz** [comment]
Hey @CoolLKKPS

Where you able to find any information about those mods and those settings?

I've researched how those mods work internally and how the game behaves with them I wasn't able to find anything that would make that min/max scrap value work. For my investigation those are just used for debugging purposes and should not be used ingame. Regardless you can achieve a similar effect by limiting the minimum and maximum **amount** of scrap and the scrap value multiplier.

Hope to hear from you soon!

**Comment by CoolLKKPS** [comment]
Ah, its ok if don't have this feature, like ur say, those are just used for debugging purposes
so i think that feature doesn't matter anymore
and btw keep urself warm, temperature is getting uh unreliable

**Comment by TheAnsuz** [comment]
Thank you, I appreciate that!

I'll mark the issue as closed. Have a nice day!
