### ISSUE TITLE
[QUESTION] Sync time with friends

### ISSUE THREAD

**Issue by pil0lo** [TheAnsuz/Lethal-Company-Configurable-Company-API#17]
When setting the game time.
Time passes quickly for friends, and for hosts, time goes by late.
How do I set this up?

**Comment by TheAnsuz** [comment]
Hey @pil0lo, I might not have understood the question. You want to know how to modify the speed at which the day passes by, right?

If so, you can change the speed of the day inside the **Gameplay** section, under **Game settings**, there you will find an option to modify the speed itself and another one to specify how the algorithm works. Keep in mind modifying the algorithm requires other players to also have the mod installed to be synchronized correctly.

Hope it helps and have fun!

**Comment by pil0lo** [comment]
It is set up like the picture.
For me, time passes slowly according to the time I set.
The friend side flows quickly at a basic speed.
But since I am the host, normal hours are my hours.
For my friend, time passes quickly and night falls quickly.

![1](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/143984023/f3949160-a0ee-4402-ad18-49db26705fd9)

**Comment by TheAnsuz** [comment]
If time is not being synchronized there might be an issue, can you send me the profile code to see if is there any issue?

**Comment by pil0lo** [comment]
Profile code???
Are you talking about the profile ID?
If the profile ID and code are different, where can I see the code?

**Comment by TheAnsuz** [comment]
Within the profile settings in your mod manager you will be able to see a button labeled **Export profile as a code**. This will allow people to download your profile with your mods and configurations.
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/84103225/50b9488f-44ae-4a9f-b9e6-a520f3e3e20d)

It will also share configurations presets you have so you can save your current settings into a preset so I can check the issue with your exact configuration values.

Hope it helps!

**Comment by pil0lo** [comment]
Profile exported

Your code: 018f05b0-6517-7a7b-9c35-e63239c83815 has been copied to your clipboard. Just give it to a friend!

**Comment by TheAnsuz** [comment]
Hey @pil0lo 

I was checking the issue but I am unable to reproduce it, I've ser up some steps for an hypotesis on what could be causing the issue, Can you check if doing the following steps makes it work correctly:

- Set the time scale to any value (for example 0.5)
- Start hosting the game
- Make your friends also change their time scale to the same value (0.5 in this example)
- Without changing the current file, your friends should join your game

Does the issue still happen after following those steps?

If you are unable to understand how to proceed contact me on discord `the_ansuz` and I'll gladly help you joining your game and testing the issue.

Thanks in advance!

**Comment by pil0lo** [comment]
Aren’t the settings saved in the save file???
Different settings for save locations 1, 2, and 3 were possible.
How do I set up friends?

**Comment by TheAnsuz** [comment]
You can start the game as usual, only modifying the time to not be a default value is required.

Your friends must go to host, click on any of the files to configure it's settings and set the same daytime speed as you have (or just copy and paste the whole settings if you prefer). Then, without changing the file (aka not clicking other save slot) they should go back to the menu and join your game (via steam or server list).

This should force the mod to cache those values from the last save slot.

**Comment by TheAnsuz** [comment]
Hey @pil0lo.

With the latest release of LCV I also made an update for time synchronization. Im not 100% sure it will fix your issue so I would appreciate some feedback about it.

Thanks in advance!

**Comment by pil0lo** [comment]
Always enable display of timer
It seems like time is different indoors.
It seems to be synchronized when I go outdoors.
