### ISSUE TITLE
[BUG] Invincible

### ISSUE THREAD

**Issue by Gragyriss** [TheAnsuz/Lethal-Company-Configurable-Company-API#18]
## **Describe the bug**
Whenever I use this mod im completly invulnerable 

## **How to reproduce the issue**
Play the game with the mod enabled
## **Mods and profile**
It's very important that you write the version of the game and the version of Configurable Company or any related mods to the issue. Use the following line:
- Game version: v50
- Configurable company: v3.3.0

Profile code: my_profile_code

## **Extra information**
Alright, so I'm 99% certain that its just the values for the new defense feature you added being inverted, because when I use 0 defense I dont take damage, and when I use 100 defense I take damage like normal. Not game breaking, but I was accidentally cheating.

Edit: so after further testing, I have concluded that there is actually no rhyme or reason as to whether or not your invincible, changing defense SOMETIMES helps, but ultimately your at the whim of of lady luck, so I just cant host with this mod anymore.

**Comment by TheAnsuz** [comment]
Hello @Gragyriss 

This issue was also reported in the discord server not long ago. I will fix it asap, sorry for the inconvenience and thank you for the time to check the reason behind the issue!

The update with the fix is being released right now.

**Comment by TheAnsuz** [comment]
I've just released a hotfix `2.3.1` that solves this issue.

I'll mark the issue as closed but feel free to open it back if you encounter any related issues.

Again, thanks for your time and report!

**Comment by Gragyriss** [comment]
Thanks, and as for the inconvenience, it was just one game night with friends, and its kind of expected with the absurd rate of development you have going, I think I should check out this discord. Thanks.
