### ISSUE TITLE
[Conflict] with LLL v1.2.0

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#19]
will cause glitch and blackscreen when loading a save

link: https://github.com/IAmBatby/LethalLevelLoader/issues/70

**Comment by TheAnsuz** [comment]
Hey @CoolLKKPS 

This issue was commented in the discord channel, I'm back home to address the issue and post a fix as soon as posible!

Due to your activity in suggestions and issues I would love to see you in the discord channel. Thanks for all the effort and reports!

**Comment by CoolLKKPS** [comment]
uh bc my region are banned discord service entirely (in 6 years ago), i can't use discord even i have discord account in previous

**Comment by TheAnsuz** [comment]
@CoolLKKPS Sorry to hear that.

I just published the patch for this issue, still I think there is a problem with LLL regarding old save-files, keep it in mind to backup your saves just in case!

Have fun!

**Comment by CoolLKKPS** [comment]
yes and, i will do more deeper test for LLL in the future, will let u know if the conflict issue happen again
