### ISSUE TITLE
[FEATURE] Can it support pressing a certain key to display within the game

### ISSUE THREAD

**Issue by ohuo133233** [TheAnsuz/Lethal-Company-Configurable-Company-API#2]
## **Feature**
I hope to modify MOD parameters within the game, rather than outside the game

## **Reason**
Adjusting some dynamic parameters in this way eliminates the need to return to the homepage

## **Alternatives**
[Some features may not be possible, if this is the case, what alternative do you think that could work?](https://github.com/Rune580/LethalCompanyInputUtils)
This mod can be set to start by pressing the button in the game

**Additional context**
not have

**Comment by TheAnsuz** [comment]
That could be possible to implement however it might take take.

Keep in mind as you say, mods will need to take this into consideration and not every option could be in the ingame menu so explicit support may be needed.

I will check if the addition could benefit the API or would just make it harder :)

**Comment by TheAnsuz** [comment]
Hello back @ohuo133233 

After consideration and investigadion, most of the features this API adds, among other things, are not currently intended to work while in game and as mentioned, the mods using this API would have to implement very hard game checks to allow modifications while in game.

I will mark this feature as not planned *for now* but maybe after some updates of the game, this feature becomes viable.

Thanks for the suggestion.
