### ISSUE TITLE
It doesnt work.

### ISSUE THREAD

**Issue by Skyler741** [TheAnsuz/Lethal-Company-Configurable-Company-API#22]
When I open the menu theres nothing in the big box to the bottem right of the screen with all the info and the tiny box to the top right of the big box just says randome letters.

**Comment by TheAnsuz** [comment]
Hello @Skyler741 

Can you provide a screenshot/profile code or console logs about the issue?

Also, are you using Lethal Company Variables?

**Comment by TheAnsuz** [comment]
Hello.

Due to the lack of activity in the issue I will mark it closed, if you have any question or the issue persists, feel free to open it back.
