### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by FrozenDice** [TheAnsuz/Lethal-Company-Configurable-Company-API#24]
The map loads and is stuck on the random seed screen, the doors dont open as well after changing values via the mod menu.

**Comment by TheAnsuz** [comment]
Hey @FrozenDice 

Are you using any other mods with your profile?
I would appreciate if you could send me the logs or console output of the game to check the issue

**Comment by TheAnsuz** [comment]
Good morning.

Due to the lack of activity in the issue I will mark it as closed, if you are still experiencing this issue pleasle feel free to open it back with the required information.

Thanks in advance
