### ISSUE TITLE
[Archived] conflict with MoreMonster and cause masker spawn to outside

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#26]
this issue don't need anything to prove actually, just something not set correctly, and another thing is, im getting a bit lazy...

**Comment by TheAnsuz** [comment]
Don't worry @CoolLKKPS you are already doing a lot by reporting these issues.

I however might need your config preset or values as all the vanilla values are obtained manually so unless the game change is pretty weird for those values to not be correctly set by default.

Also I might not understand about the masked enemy outside, they can go outside anytime.

**Comment by CoolLKKPS** [comment]
[ConfigurableCompany (in bepinex).zip](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/files/15171473/ConfigurableCompany.in.bepinex.zip)
[Configurable Company (in locallow).zip](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/files/15171474/Configurable.Company.in.locallow.zip)
[LogOutput.txt](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/files/15171478/LogOutput.txt)

ok i send those files for u, u don't need to worry about too much about the log bc i filted it by using LogNeuter, u also can use my LogNeuter config to filter the log

[BlueAmulet.LogNeuter.zip](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/files/15171501/BlueAmulet.LogNeuter.zip)

**Comment by CoolLKKPS** [comment]
the only thing u have to check is this log: `[Info   : Unity Log] Spawned enemy: Masked`

this log means enemy spawned outside not inside, and also ignore modelreplacementAPI error log, that did nothing useful

**Comment by TheAnsuz** [comment]
@CoolLKKPS I find myself unable to replicate the issue, I may have not correctly configured log neuter.

Can you consider sending me the profile code (save the config from the file where you encountered this issue as a preset) to check?

Thank you in advance

**Comment by CoolLKKPS** [comment]
ok but need more time now, bc rn im updating my modpack so need to take some time

**Comment by CoolLKKPS** [comment]
@TheAnsuz hope u don't mind the language issue, here's the r2z file
to make sure everything work correctly, i choose to export as a file
[Main_1714548015150.zip](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/files/15174779/Main_1714548015150.zip)

**Comment by CoolLKKPS** [comment]
if u need to switch back to english, just simply disable LCTC and LCPoster mods

**Comment by CoolLKKPS** [comment]
weird... i just delete some suits related things and this issue fixed? weird...

**Comment by CoolLKKPS** [comment]
will keep tracking this issue, if i found something i will let u know

**Comment by TheAnsuz** [comment]
Hey @CoolLKKPS 

Thanks for all the feedback for the issue. Let me know if the issue persists in the future and feel free to open back the issue!

**Comment by CoolLKKPS** [comment]
@TheAnsuz 
> if u click on "Reset to default values" but forgot to "Save configuration", this glitch will trigger, and u must restart the game and > correctly reset the config to fix this issue

might also happen when u create a lobby twice

**Comment by CoolLKKPS** [comment]
@TheAnsuz update, only happen when u host the game, and not join the game at the first time (without restart the game client)

**Comment by CoolLKKPS** [comment]
Update, only happen when hosting the game again, and they must enter to another lobby at least once (or host a lobby at least once), without restarting the game

**Comment by TheAnsuz** [comment]
Thanks for the report @CoolLKKPS 

If you are not hosting, LCV should behave just like a vanilla client, also LCV will not block the connection of anyone to the host even if they don't have the mod, there might be another mod issuing that. 

I'd like to know if you find any errors when joining the host and checking if the issue happens with only LCV if possible.

Thanks in advance!

**Comment by CoolLKKPS** [comment]
uh only happen when hosting the game, and when join the first lobby after launched the game, nothing will happen, so should be something wrong when player dc and quit the lobby, this issue most likely can trigger when player hosting the lobby twice without restarting the game

**Comment by TheAnsuz** [comment]
So to replicate the issue:

In order:
- Click host game
- Leave game
- Join another game as client
- **You won't be able to join**

Is that correct @CoolLKKPS ?

**Comment by CoolLKKPS** [comment]
no, just host the game twice, and u should be can able to reproduce, only just need 1 game process

**Comment by CoolLKKPS** [comment]
btw level moon is art

**Comment by TheAnsuz** [comment]
I can't seem to replicate the issue, there might be other mod causing it.

Can you send profile code?

**Comment by CoolLKKPS** [comment]
@TheAnsuz ahh, uh will do a real quick check, and then i will send more Cleaner modpack for u

**Comment by CoolLKKPS** [comment]
wait actually i already done that, Link: https://1drv.ms/f/s!AlwrljXcImfClQzhyITXFCZkPl3U?e=AT99S8

**Comment by CoolLKKPS** [comment]
to reproduce:
1. enable all the mods except vr mod
2. start hosting the lobby and route to art level, and quit the lobby when in-game time are passed 18:00 pm
3. start hosting the lobby again and do the same things, and then u should can see `[Info   : Unity Log] Spawned enemy: Masked` rn

i have to say this bug is a little bit hard to find, i am not sure following this order can reproduce but i am more sus for MoreMonster mod

**Comment by CoolLKKPS** [comment]
@TheAnsuz ok new progress, it's more like a conflict with MoreMonster, and that mod is quite a bit old now

**Comment by TheAnsuz** [comment]
To check if there is any issue with LCV or Configurable Company I might need the configuration settings to check

**Comment by CoolLKKPS** [comment]
@TheAnsuz confirmed MoreMonster issue, since that mod is out of maintain, so i won't keep tracking this issue
same order to reproduce, and i don't think need to send configuration files anymore bc those are all default
and thx for ur reply and keep tracking this issue, even this issue is really unnecessary to solve!

**Comment by TheAnsuz** [comment]
@CoolLKKPS I can't guarantee that is a compatibility issue and not an issue with just how the game updated with the time as that mod seems to be for v49, not v50 which has changed some stuff.

My recomendation would be to get rid of that mod, after all all the settings you need are covered by LCV (per request of another player a long time ago)

**Comment by CoolLKKPS** [comment]
got it!
