### ISSUE TITLE
[QUESTION]  Should I click load preset every time

### ISSUE THREAD

**Issue by BidloTupa** [TheAnsuz/Lethal-Company-Configurable-Company-API#28]
## **Question**
Hi. Do I constantly need to click on the "load preset" button in order for my configs to work?
![Снимок экрана 2024-05-04 201753](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/167890038/d69b4dae-8bab-48cc-88b3-6b1fbf9f89b7)

**Comment by TheAnsuz** [comment]
Hello @StrayPMC 

It might be a bit confusing, presets are only for you to save configurations with your profile, you can have as many as you want and they are not related to the current settings (Consider them as creating a backup for your configs).

On the other hand, configurations are different between each save file slot, with that in mind, you only need to save the configs normally and they will be applied until you decide to modify them.

Hope this helps. Feel free to ask anything you need!

**Comment by BidloTupa** [comment]
@TheAnsuz I use this mod together with the mod [LCBetterSaves](https://thunderstore.io/c/lethal-company/p/Pooble/LCBetterSaves/), and every time I delete one of the saves (see screenshot) and select "new file" I have to press "Load Preset" again. Is there any way to solve this, or will you have to remove this mod for convenience?
![Снимок экрана 2024-05-04 225944](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/167890038/764043c4-e681-4b53-89c4-d6d0fe277aa4)

**Comment by TheAnsuz** [comment]
@StrayPMC This mod is compatible with better saves. Can you check if inside the save-files folder you can find the corresponding configuration files?

The save-files are saved inside `AppData/LocalLow/ZeekerssRBLX/LethalCompany/` and they are called `LCSaveFile...`.
The configurations are saved in a folder called `Configurable Company/<Your profile name>/` and they have the same name that their corresponding save file has with a **.ccfg** extension, check if for each save file there is one of those, if not, they are not being saved when you delete the file.

**Comment by TheAnsuz** [comment]
Hello @StrayPMC 

I will be closing the issue as there has been no updates or information.

Feel free to reopen the issue if you need.
