### ISSUE TITLE
[BUG] Mod Conflict with StarlancerMoons

### ISSUE THREAD

**Issue by Instaplayer** [TheAnsuz/Lethal-Company-Configurable-Company-API#29]
## **Describe the bug**
With StarlancerMoons installed alongside LCVariables most vanilla enemy spawn power defaults and spawn capacity defaults are set to 0.
Trying to manually set the variables back to their proper values only affects spawn capacity. Spawn powers remain at the new "default" 0 resulting in excessive monster count
## **Mods and profile**
- Game version: v50
- Configurable company: v3.4.0
- LethalCompanyVariables: v2.3.2
- StarlancerMoons: v1.7.1 (however from my testing the issue persists all the way back to version 1.5.0)

Profile code: 018f4e54-1886-3e03-0074-ff82e3613153

## **Extra information**
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/94839182/7578f14f-809b-4a13-b885-fef06eca1423)
Example console output after manually setting all spawn powers of 0 to a value of 1 and all spawn capacities of 0 to a value of 5

+ the log output from the same game
[LogOutput.log](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/files/15222095/LogOutput.log)

**Comment by TheAnsuz** [comment]
Hello @Instaplayer 

The spawn power might be being overriden by the starlanzer mod, there is currently a related issue regarding the spawn power not being set after modifications.

Does the value in the menu for spawn power set to 0 as default values?

**Comment by Instaplayer** [comment]
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/94839182/19e08d73-ea66-44d8-b9be-1a49acd67737)
It does

Clicking Reset to default values sets most of them to 0
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/94839182/98e03be3-267b-4580-aa4a-81a4eedb478e)

**Comment by TheAnsuz** [comment]
That might be because of some custom moon messing with the default spawns for enemies.

It is being worked on to prevent these cases, will be fixed in the next major update!

**Comment by TheAnsuz** [comment]
Hello @Instaplayer 

With the latest update of LCV this issue should be fixed, if you are still encountering this issue pleasle let me know or reopen the issue!

Thank you in advance
