### ISSUE TITLE
[BUG] name here

### ISSUE THREAD

**Issue by thechickenwithlegs** [TheAnsuz/Lethal-Company-Configurable-Company-API#3]
## **Describe the bug**
What happened that made you think something does not work as intended.
it was open when not in host mode and was unusable, and also read in a text box "asadasfasfwafagagaggaadfsadadfaf"

## **How to reproduce the issue**
Try to explain what you did to reproduce the issue. If you down know what you did ir is unclear, leave it blank
start the game

## **Expected behavior**
to start lethal company and open the host page to be able to edit configs

## **Mods**
Write the list of mods you were using when this happened
general mods that havent affected it before at all

## **Extra information**
Anything else you want to add. You can leave it empty
this was after updating

**Comment by TheAnsuz** [comment]
Could you provide with an screenshoot from the console and game? 
Make sure to have the latest Configurable company version (3.2.1)

**Comment by TheAnsuz** [comment]
Hello.

A similar bug was addressed in the latest release.
Could you check if the issue still occurs?

Thanks.

**Comment by TheAnsuz** [comment]
Hello @thechickenwithlegs 

Some people confirmed in the discord this was fixed as part of the **2.0.1** patch. I will close the issue, if you find the same issue occuring or a similar one, feel free to reopen it and I will take an in-depth search.

Thanks for reporting this issue.
