### ISSUE TITLE
[QUESTION]  Custom interior configs?

### ISSUE THREAD

**Issue by BidloTupa** [TheAnsuz/Lethal-Company-Configurable-Company-API#30]
Hi. I wanted to ask if it is possible to customize the rarity of spawn for custom interiors in this mode?

**Comment by TheAnsuz** [comment]
Hello @StrayPMC 

That feature is still work in progress, so for now you are not able to modify the chances sadly.

If you want any feature to be added feel free to open a suggestion!

**Comment by BidloTupa** [comment]
@TheAnsuz And I also wanted to ask if there is any way I can share my preset? 
And is it possible to make my preset apply to all my save lots automatically?

**Comment by TheAnsuz** [comment]
Hi @StrayPMC 

Yes, you can share configurations, when you create a preset it gets shared with your profile code/file. You can also copy it to clipboard and paste it although the file will be large!

You can apply your configs on all saves by saving the configs you want as a preset and clicking "load" in the slot that you want to apply configs to.

Hope this helps!

**Comment by TheAnsuz** [comment]
Hello @StrayPMC 

As there has been no updates on the issue I will mark it as closed. If you have anything related to the issue that you need a solution for, pleasle feel free to reopen the issue with the comment or create a new one.

Thanks in advance!
