### ISSUE TITLE
[BUG] Map spawnable

### ISSUE THREAD

**Issue by kiloix** [TheAnsuz/Lethal-Company-Configurable-Company-API#33]
## **Describe the bug**
*When I open the menu and modify the number of turrets (entire number), there has not effect in the facility.*

## **How to reproduce the issue**
∅

## **Mods and profile**
- Game version: v50
- Configurable company: v3.4.0

Profile code: 76561198966762690

## **Extra information**
∅

**Comment by TheAnsuz** [comment]
Hello @kiloix 

How are you saving the configuration after making que changes?

Also that profile code seems to not be working, can you check if it is correctly written?

Thanks in advance!

**Comment by kiloix** [comment]
## **Saving configuration**
I save configuration by selecting button "save configuration" this is due by the bolding words. 

![Hello](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/f0ea4c00-0a1f-4590-9740-f0b9db90370e)



## **Profil code**
Of course, my (new) profil code is : 1006496962

**Comment by TheAnsuz** [comment]
Hello @kiloix 

Are you sure that's the profile code? Seems to not be working, profile codes have the following format:
056fabf6-1551-a8f0-51cc-013852b6a604

Also, could you create a preset from the save file so your configs get exported with the profile?

Thanks in advance!

**Comment by kiloix** [comment]
## **Profile code**
Oh ! Sorry, i put the code here : 018f7a5f-5a05-8273-9bda-0287537ec49f

## **Presseting file**
Here, the location of mod's file :
![liiilo](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/a602c5fc-f1b0-406b-aae3-996c69651586)
-Tools: *Browse profile folder* (thunderstore, r3mmodman), *Load preset, save preset* (lethalcompanyvariable).
-Launching:

Let's get statrted !


When i click here, theree is no effect.
![liilo2](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/7609d34e-cc77-4a68-9a71-3886fea39c89)


In my opinion, I think that the folder is save:
![liilo3](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/94ab345c-adcf-4f5d-acb8-db3d687de4cf)

There is not adding folder in the files when i did that..

I saw a video explaining the download of a saving file editor. Maybe i supposed to do that.

## **Link**
[https://www.youtube.com/watch?v=7YBxDNyjrXo](url)

**Comment by TheAnsuz** [comment]
Hello @kiloix 

Presets are saved inside `BepInEx/config/ConfigurableCompany/<preset>.ccfg`

> Clicking load preset when the **default** one is selected will just revert your values to default.  
> You might want to create a new one with your settings and then save/load that one.
> **Save preset** will save your current settings to the selected preset file name.  
> **Load preset** will overwrite your current settings with the stored ones.  

Configurations for each save file are not saved within the save-file, they are saved inside
`.../AppData/LocalLow/ZeekerssRBLX/Lethal Company/Configurable Company/<profile-name>/<file>.ccfg`

I also saw that you have LC_API which if I remember correctly is deprecated and might cause issues with your game and other mods. I'd suggest to search for an updated mod that covers the features that you are using from that mod.

Let me know if this helps you!

**Comment by kiloix** [comment]
Thanks to giving these informations, only, I meet a the same problem, let me explain:
I saw in my folder that only my first name of document's mod appeared. Plus, I don't see _Localow_ or _preset.ccfg_ in my PC.
I'm not experimented (or unless) in programation. I've to suggest this topic in question category. 🤣

## *Photography**
This image shows the "way" to acces in my mod list from the death memory of my computer. You see that only one folder appears whereas two (or three) folders.
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/9e5b33c4-9b82-4c65-8aad-5332447776a2)

Thanks in advance !

**Comment by TheAnsuz** [comment]
Hi @kiloix 

Under the shown folder you should be able to locate some of the needed folders as inside that folder you can locate another folder called `BepInEx`, if you navigate though these folders `BepInEx > config > ConfigurableCompany ` and you should be able to see the presets.

To locate the `locallow` folder you should search **outside** this folder as it is located in other section of your computer, the whole path should look like this: `C:\Users\Usuario\AppData\LocalLow\ZeekerssRBLX`

Also I want to add that I wasn't able to reproduce the issue with the turrets, again, I would love to join you in a game to check what LCV is doing and if turrets are not spawning.

If you want to accelerate the process to solve the issue feel free to contact me on discord to help you in real time `the_ansuz`.

**Comment by kiloix** [comment]
## *implementing error*

I search the code for lethalcompanyvariable by pressing **windows + R** but it doesn't work.
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/84f6249e-3f75-4e65-92c9-1a686a06ab68)

Traducing : windows can't find ***BepinEx***, (😳 Big issue because this software permits to launch the terminal of lethalcompany's mods) check out if your words are correct then retry. 
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/ae8da4ee-4f6b-4cd7-bba0-631612987c7c)

I copy the auther way.

![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/40a79017-5a22-4ca1-918d-f2911448468e)

Same effect.

![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/169745114/244b79ef-4d30-4c12-b884-4c9c3a1fad23)

Can you help me in my game (vanilla or by modded gaming) ? I'll add you in discord app.

**Comment by TheAnsuz** [comment]
This issue was handlded using discord.

Resolved in being an issue with compatibility with other mods, should be fixed with the latest update!

If the issue still persist feel free to reopen the issue with information about it.

Thanks in advance!
