### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nWesa** [TheAnsuz/Lethal-Company-Configurable-Company-API#35]
Whenever i open the menu, the search bar is automatically filled with "asjdhfgsjdhfgsjhdgf" and i cant configure anything because of that
I reproduced the issue by simply reinstalling the mod and i even factory reset my computer and nothing has changed. 

## **Mods and profile**
I only have configurable company installed.
- Game version: v50
- Configurable company: Latest

![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/165290818/cd836910-7a7e-445b-a66c-8d2e290f4b28)

**Comment by TheAnsuz** [comment]
Hello @nWesa 

Can you see any errors in the console? That issue might be caused due to an incompatibility with some other mod. Are you only using Configurable company or any other mod (even disabled ones)

**Comment by TheAnsuz** [comment]
Hello @Julen2010XD 

Due to the lack of activity in the issue I will proceed to close it.

If I can recall the issue is being caused by not having both Configurable company and Lethal Company Variables installed.

If you are still encountering this issue feel free to open in back.

Thank you.
