### ISSUE TITLE
[BUG] Traps multiplier settings not working

### ISSUE THREAD

**Issue by Fooxynn** [TheAnsuz/Lethal-Company-Configurable-Company-API#37]
## **Describe the bug**
The configs for traps multiplier doesn't seems to work. Even when putting big values, there is a normal amount of those spawning.

## **How to reproduce the issue**
Simply change the multiplier for traps (**Planets** > **Global** > **Map spawnables**) to let say a very high number and play.

## **Mods and profile**
- **Lethal Company v50**
- _BepInExPack v5.4.2100_
- _ConfigurableCompany v3.4.0_
- _LethalCompanyVariables v2.3.2_

## **Extra information**
I disabled all my mods to see if the feature was at least working by itself, but no. I was checking the amount of traps using Imperium normally, but with the last test i disabled it too to. So couln't really know the amount of traps but i did not see a single mine when running a bit while the setting was on 100.
In some of the tests, i even had zero trap inside. So it is surely broken as, by what's written, by having a high number it should spawn a minimum amount.

**Comment by TheAnsuz** [comment]
Hello @Fooxynn 

This issue will be fixed with the next release of the mod (which will be published in a few days after all the required testing is finished)

Thank you in advance!
