### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Swedish-guy** [TheAnsuz/Lethal-Company-Configurable-Company-API#38]
![bild_2024-06-07_185816824](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/172066081/1b8b1267-10a6-4740-936c-9bbb96db0570)
(view picture for issue)
T H A T happend

**Comment by TheAnsuz** [comment]
Hey @Swedish-guy 

That might be because LCV did not work propertly.
Can you share the logs of the game?

Thanks in advance!

**Comment by Swedish-guy** [comment]
i sent that right before i went off so sorry for the wait
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/172066081/ea10ea32-3162-4222-8326-b4314fce6333)

![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/172066081/b89dcb95-1274-477f-b42b-494cb3aeac72)
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/172066081/21486da5-b1bc-41f7-bc1e-b07751d63eb2)

tried my best adn right after that lethal company crashed

**Comment by Swedish-guy** [comment]
tried my best

**Comment by TheAnsuz** [comment]
Thanks @Swedish-guy

Sadly I can't really see anything relevant in those logs, can you add the log file? Located inside the Steam's lethal company game directory. If not I will need the profile code to import the modpack and test the issue myself.

Thanks for your time :)

**Comment by fletchermed1** [comment]
I have this same issue and it happens even when I have Configurable Company as the only mod

**Comment by TheAnsuz** [comment]
@fletchermed1 @Swedish-guy 

Pleasle, keep in mind that Configurable Company is the API for other modders, there are some mods that use it to implement their configurations, use [Lethal company variables](https://thunderstore.io/c/lethal-company/p/AMRV/LethalCompanyVariables/) among configurable company to see the official implementation that you can see in the images.

If you already have **both** the mods and you still don't see any configurations, plasle provide me with the profile code so I can check the issue.

Thanks in advance.

**Comment by TheAnsuz** [comment]
Hello @Swedish-guy 

Due to the lack of activity in the issue I will proceed to close it.

If you are still encountering this issue feel free to open in back.

Thank you.

**Comment by Swedish-guy** [comment]
Close it, thank you
