### ISSUE TITLE
[QUESTION] Is my file incompatible?

### ISSUE THREAD

**Issue by acps87** [TheAnsuz/Lethal-Company-Configurable-Company-API#39]
I am having issues using the mod. Heres my snapshot of my window: 

![Screenshot 2024-06-17 173116](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/17233558/0c5e3594-eaa9-4e1f-bf9e-7ffacb5a49a3)

It seems that i can never get to the settings of my save file. Tried several different saves and asked a friend to try it too however we cant figure it out. None of the pages appear with the settings and hitting any of the buttons dont do anything.

Thanks in advance for the help!
~Acps

**Comment by TheAnsuz** [comment]
Hello @acps87 

Save files should not be incompatible, rather some mod may be interfering with your instance, can you let me know which mods are you using?

If you could also share the logs I would appreciate it.

Thank you :)

**Comment by acps87** [comment]
I did try running without any mods and still had the same issue not being able to read the save. Where are the logs saved at so that I can send them to you? Ty

**Comment by TheAnsuz** [comment]
Hi @acps87 

Can you make sure you also have [Lethal company variables](https://thunderstore.io/c/lethal-company/p/AMRV/LethalCompanyVariables/) installed?

Seems like some people is having trouble with this, you need both the mods, configurable company is an API for other modders to implement their configurations, in this case, lethal company variables is the official implementation which contains **a lot** of parameters.

Let me know if are still experiencing this issue!

**Comment by acps87** [comment]
Oh wow now I feel silly, definitely looked over the fact you needed both to work. Sorry for taking up your time and ty for the quick help!

~Acps87
