### ISSUE TITLE
Can't edit some settings

### ISSUE THREAD

**Issue by Gragyriss** [TheAnsuz/Lethal-Company-Configurable-Company-API#4]
## **Describe the bug**
I am unable to click on the some of the buttons to access settings, some work while others don't, anything in "enemies" is broken, "gameplay" is fine, the only thing in "extras" working is "ship", and all of "planets" is working. This is in version v2.0.1 by the way.

Edit: I reloaded and am now getting the same bug as in the other '[BUG] name here" post, where nothing is coming up and the save file is a bunch of random letters.
## **How to reproduce the issue**
open the config menu

## **Expected behavior**
not sure what this is asking

## **Mods**
Thunder store mod list: "018eb0d5-4f51-7598-b363-8dd961e8eef8"

## **Extra information**
Just wanted to say thanks for your mod, its *normally* amazing and makes hosting with friends or randoms much more fun as it allows for re balancing while being incredibly easy to use and can do a lot. Seriously, my favorite mod.

**Comment by TheAnsuz** [comment]
Hello @Gragyriss 

Sorry for the inconsistency with the latest release, I will look into the issue and fix as soon as possible.

Make sure to also have the latest version of Configurable Company as it's known it had a bug before.

**Comment by TheAnsuz** [comment]
Hi @Gragyriss 

This issue was addressed with the latest release of LCV. Everything should work as intended.

I will mark the issue as resolved, however feel free to open it back if you encounter a similar issue in the future.

Thanks for the report!
