### ISSUE TITLE
Menu not working.

### ISSUE THREAD

**Issue by Julen2010XD** [TheAnsuz/Lethal-Company-Configurable-Company-API#40]
## **Issue**
When opening the menu, the menu options do not show up.

## **How to reproduce the issue**
I don't know how this issue happened.

## **Mods and profile**
- Game version: v50
- Configurable company: v3.3.0

Profile code: 019050df-d54e-8ea6-e325-c3b86849a1c3 

## **Extra information**
Next to the LCSaveFileX ("X" representing the save file number) is a long unerasable text that goes "asdagsagsagda..." until the end of time. 
![20240625213149_1](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/173843128/b6c80f21-7fa3-407d-9a5d-ef274335856f)
Provided a screenshot for further explanation.

Thanks you in anticipation helping fixing this issue, best regards.
Julen.

**Comment by TheAnsuz** [comment]
Hello @Julen2010XD 

Pleasle, make sure you also have LethalCompanyVariables installed :)

If the issue is happening while also having lethal company variables installed, pleasle let me know.

Thank you in advance.

**Comment by TheAnsuz** [comment]
Hello @Julen2010XD 

Due to the lack of activity in the issue I will proceed to close it.

If you are still encountering this issue feel free to open in back.

Thank you.
