### ISSUE TITLE
[BUG] Receiving errors, mod not working

### ISSUE THREAD

**Issue by goofygoober719** [TheAnsuz/Lethal-Company-Configurable-Company-API#41]
Some tabs on the configuration menu do not drop down, and the game remains entirely default regardless of what values are set for the variables. I get these errors on startup.

![Screenshot (641)](https://github.com/user-attachments/assets/42b54ef9-55ed-4298-a801-846f465a9a24)

- Game version: v56
- Configurable company: v3.4.0
- LethalCompanyVariables: v2.3.2

Profile code: 0190c24b-a120-dafd-909d-e5787bb09881

**Comment by TheAnsuz** [comment]
Hello @goofygoober719.

After trying to import your profile seems like everything is working fine. For the errors you have shown me seems like the preloader (located in BeepInEx/patchers) did not work correctly.

I'd recommend you to reimport your own profile just in case some weird error of file is messing up your profile. If after doing so the error still occurs, I would appreciate if you could send the whole logs of your profile to check things out.

Thank you in advance!

**Comment by goofygoober719** [comment]
Thank you very much, I looked into it and realized that the preloader wasn't in the proper location. After putting it where it was supposed to be, everything seems to be working properly now.

**Comment by TheAnsuz** [comment]
Perfect!

I will mark the issue as closed, let me know if you have any other issues!

Thank you for using the mod!
