### ISSUE TITLE
[BUG] Planet config options not taking effect

### ISSUE THREAD

**Issue by wooooyeahhhh** [TheAnsuz/Lethal-Company-Configurable-Company-API#42]
## **Describe the bug**
When an option for any planet is changed it will not make any changes upon starting the game. It seems to be only planets as the other config options do make changes in game.

## **How to reproduce the issue**
Change a planet config and save it.

## **Mods and profile**
- Game version: v56
- Configurable company: v3.4.0

**Comment by TheAnsuz** [comment]
Hello @wooooyeahhhh 

What configuration are you trying to change for planets that is not being used?
Also, do you have any other mod that updates similar settings for planets?

Let me know And I will look into the issue!

**Comment by wooooyeahhhh** [comment]
@TheAnsuz configurable company and LCV are the only mods used.

I tested it by massively increasing the scrap amounts on experimentation and assurance and scanning in the ship and it showed no difference from vanilla values. Additionally the max enemy power and factory size make no difference.

**Comment by wooooyeahhhh** [comment]
@TheAnsuz I fixed it. It was an error in my install.

**Comment by TheAnsuz** [comment]
Alright @wooooyeahhhh 

I'd recommend using a mod manager to avoid such as problems, otherwise, make sure to have the 3 dlls the mod uses, the preloader, the base dll and the compatibility dll
