### ISSUE TITLE
[BUG] Can't write a name for a preset

### ISSUE THREAD

**Issue by Friskzips** [TheAnsuz/Lethal-Company-Configurable-Company-API#43]
## **Describe the bug**
When i try to write a preset name in the input field an error in the console at "21:17:12.8816086" get spammed and it doesn't seem like the input field work properly.

## **How to reproduce the issue**
Open the game and click the input field and press a character in your keyboard.

## **Mods and profile**
- Game version: v56
- LethalCompanyVariables v2.4.0
- Configurable company: v3.4.0

Profile code: 0190e69c-2df3-1c47-7b4f-8b04a86f8b40

## **Extra information**
![Lethal Company 24_07_2024 21_44_46](https://github.com/user-attachments/assets/e60f1d9c-41c3-4f48-a7e9-9a7759a9c8fe)
![Screenshot 2024-07-24 232533](https://github.com/user-attachments/assets/90532c0c-8880-45d1-bc02-7814cab2e148)
[LogOutput.log](https://github.com/user-attachments/files/16367589/LogOutput.log)

**Comment by Friskzips** [comment]
Im starting to think that this is a problem only for me lol.
I did a fresh install with the new version and it still giving me issue
I send the video
first error is when I clicked the input field
the rest was just with a press of a key while focused the input field

https://github.com/user-attachments/assets/8ffbe444-f2f2-48ab-b83b-8840dedc4196

[LogOutput.log](https://github.com/user-attachments/files/16372065/LogOutput.log)

**Comment by TheAnsuz** [comment]
Hi @Friskzips 

Seems like a problem with unity itself, I will try to find a solution but I need some extra information.
What type of keyboard do you use? Is it english language?
Can you check if using another game profile does cause the same issue?
Can you try verifying your game files (from Steam)?

Thank you in advance!

**Comment by Friskzips** [comment]
I verified the file, and it didn't do anything.
I could try using another profile, but as I said, I literally did a fresh install on another profile and it still didn't work, so I don't think it's going to work anyway.
Keyboard: https://www.trust.com/en/product/22457-gxt-845-tural-gaming-combo
My keyboard layout is Italian.
I did a test with another keyboard and english layout but it didnt changed anything but I find out that I was able to save my input, so I think it's just a problem with rendering the text or something like that.


https://github.com/user-attachments/assets/1d277aa0-4388-4e9a-9652-ce4c638f9e76


[LogOutput.log](https://github.com/user-attachments/files/16377644/LogOutput.log)

**Comment by Friskzips** [comment]
I am gonna check later if there is a difference with another profile

**Comment by TheAnsuz** [comment]
Alright thanks @Friskzips 

Seems like an issue with TMP (the API for text input) I will try to fix it but as Im not able to replicate the issue it might take me some time.

Thank you for your time and effort!

**Comment by Friskzips** [comment]
i tried to mess around with UnityExplorer and apparently i found a workaround
idk if im assuming right but it looks like a problem with the text size
at 1:27 i find the workaround.

https://github.com/user-attachments/assets/4cf26179-9f48-443c-899c-d7e6cd53c6a0


even the log spam stopped

**Comment by TheAnsuz** [comment]
Thats some weird issue @Friskzips 

What is the resolution of your monitor? I'll try to implement your workaround in the base mod after testing that it does not break anything.

Thank you for your effort!

**Comment by Friskzips** [comment]
my monitor resolution is 1366 x 768
the windows resolution is 1920 x 1080
glad to help

**Comment by Friskzips** [comment]
@TheAnsuz I found the root of the issue! 
windows has a setting on system>screen to resize text, app and other elements
my recommended value is 150% but i use 100% because its too big with 150%, but i tried using 150% and it worked without a problem.
I am obviously not gonna use 150% but it's cool that i know the problem.



https://github.com/user-attachments/assets/2c536c19-6f45-4720-979a-72ef9d4f24a1

**Comment by TheAnsuz** [comment]
Hey @Friskzips 

Yea, seems like an issue on how the scaling is applied to the interface, I've already tested some changes but I might need your help to confirm that this issue is solved with a posible patch for configurable company.

Thanks for all the info!

**Comment by Friskzips** [comment]
ok

**Comment by TheAnsuz** [comment]
Hello @Friskzips 

I have updated Configurable Company with the intention of fixing your issue among other changes.
I would love to hear from you in regards of a test to check whenever the issue has been fixed or not.

Is it possible to discuss this privately so I can send you a private beta with the changes?
_I'm not making it public as it's a development build_

Thank you in advance!

**Comment by Friskzips** [comment]
sorry for not answering but yea i tried the new version and it works, thanks.

**Comment by TheAnsuz** [comment]
No worries! Glad to hear it is solved
