### ISSUE TITLE
[BUG] Masked spawning outdoors

### ISSUE THREAD

**Issue by goofygoober719** [TheAnsuz/Lethal-Company-Configurable-Company-API#46]
In the base game, the masked enemy can only spawn on Adamance, Rend, Titan, and Artifice. On these moons, the masked is considered an interior entity and only spawns via vents.
Whenever masked spawns are enabled on any other moons besides those 4, they do not appear to be considered interior entities, and instead spawn outside.
The config menu also lists the masked as being an outdoor nocturnal enemy, despite them only ever spawning as an interior entity in the base game.

This issue can be observed consistently on any moon besides the 4 specific moons that include the masked by default.
If the masked enemy is enabled, they will not be included in the interior spawn cycles and will not spawn through vents. When the first spawn cycle occurs on any of these moons, you can also see that the masked enemy is not listed alongside all the other interior entities in the console, and does not appear in the console as a spawnable entity whenever an indoor spawn cycle occurs. Any masked that do spawn will only spawn outside via nighttime spawn cycles.

- Game version: v56
- Configurable company: v3.4.0
- LethalCompanyVariables: v2.4.0

Profile code: 0190e9d4-3a82-6ef7-b8d2-b91b64530fe3

To reiterate, this is only an issue on Experimentation, Assurance, Vow, Offense, March, Embrion, and Dine. The masked spawns work as intended on Adamance, Rend, Titan, and Artifice.

**Comment by TheAnsuz** [comment]
Hello @goofygoober719 

I will check the issue, are you using any other mod alongside LCV that could modify enemy behavior or spawning?

Thanks in advance

**Comment by TheAnsuz** [comment]
Hello @goofygoober719 

This issue is addressed and fixed with the upcoming release of LCV (2.5.0).

If you encounter this issue with this new upcoming release feel free to reopen the issue.

Thanks you for your time!
