### ISSUE TITLE
[FEATURE] Moon scrap probabilities

### ISSUE THREAD

**Issue by goofygoober719** [TheAnsuz/Lethal-Company-Configurable-Company-API#47]
I have no idea how much of a handful it would be to implement this, but I would love to see configurable scrap probabilities for each moon, similar to what is currently available for enemy spawns.

This is more or less the only significant set of variables I can think of that isn't already in the mod and hasn't already been suggested, so I think it would make a great addition.

**Comment by TheAnsuz** [comment]
Hello @goofygoober719 

That feature is planned for the next version of LCV which should come before soon.

Thanks for the suggestion!
