### ISSUE TITLE
This is simply a suggestion on compatibility

### ISSUE THREAD

**Issue by Donut-man1** [TheAnsuz/Lethal-Company-Configurable-Company-API#48]
## **Feature**
I would like to request compatibility with vr if that would be possible

 _i was unsure if this would be considered a bug since its simply an issue with vr compatibility with your mod_

## **Reason**
i was running some tests for my modpack and your wonderful mod that i utilize a lot is suffering some issues. In no way am i saying that this is your problem or that i see entitlement to have this added, i simply would love for this mod to be compatible with VR.

## **Alternatives**
I am unsure of any suggestions to make, i am not a modder

With that in mind though, i was wondering if you could make the **PredictAll--------Enemies_Transpiler** configurable? this line of code is mentioned in the first screenshot

**Additional context**
To assist in the possible contemplation of adding these adjustments, I will provide some screenshots of the code and what goes wrong whilst booting up the game below
I would like to add that, again, in no way am i a modder, so i have no clue if some of these screenshots are in relation to your code but I'll do my best to identify the correct errors

**the main error** 
![image_2024-08-04_070944776](https://github.com/user-attachments/assets/8f758b3d-0713-455c-91a2-4570c1f5ac2a)

**the whole code including your mod**
![image](https://github.com/user-attachments/assets/496bbb0b-cdaf-4bc7-92a2-5cf57ade915e)

**seemingly unrelated errors (?) (may be useful to include here)**
![image](https://github.com/user-attachments/assets/450940f9-7ce1-4f33-a709-2f812ddee4bb)
![image](https://github.com/user-attachments/assets/a90e38f3-4f69-44ee-95da-da08dba19084)
![image](https://github.com/user-attachments/assets/b9768777-c90f-4acf-93fc-1d11ccd009fd)

oh! and the main issue is that the user is unable to interact with the terminal inside the game because the screen is black and you cannot type on it even when on PC. I have no clue how this relates to your mod specifically, other than the mere fact that the terminal is unusable only when your mod is active.

I hope you consider this suggestion and i would be very happy to see this fixed in vr! thank you so much for reading this in the first place

**Comment by TheAnsuz** [comment]
Hello @Donut-man1 

I'm not sure what issue are you having with VR as I have no equipment to test it. Let me know what issues with that are you experiencing.

On the other part, I don't understand what you mean with the `make the PredictAll--------Enemies_Transpiler configurable` request, I will gladly fix any issues with that but i'm unsure what is the requirement.

For the error you are having, that might be the root of some issues, do you mind sending the profile code to check? Seems like other mod is modifying some stuff leading to compatibility issues.

Thank you in advance!

**Comment by Donut-man1** [comment]
Hello @TheAnsuz and thank you so much for your response,

The only issue seems to be when I enable the LethalCompanyVariables mod (alongside the ConfigurableCompany mod), the Terminal for switching moons, purchasing items, etc. is inactive and broken. When interacted with whilst in VR, the terminal screen is black and the popup keyboard is unusable save for a small exit button. When interacted with on PC, the screen is black and you are unable to exit the terminal, being effectively softlocked and having to leave and reload the save.

I apologize for the misunderstanding, I was simply curious if it was at all possible to allow the user to configure that line of code? I'm unsure of how this will fix the errors, or how this will even fix the problem, but it seems to be the only issue that appears in relation with the ConfigurableCompany mod.

I am happy to share the profile code! I made the VR mod ask whether or not you're playing on VR so you should have no issues on a computer. I do have a couple warnings though; 

Firstly, your mod will be enabled when I send you the code and you will get softlocked and have press escape and quit in order to restart your game if you interact with the terminal. Feel free to disable and enable any mods if you see a problem with them! 

Second, I am aware of the many lines of red code and even with these errors appearing, my VR still works to play the game, the only issue is when I enable the LethalCompanyVariables mod, the terminal becomes blank.

Finally, the disabled mods at the bottom of the pack are either already broken, annoying but useful, or for a different version of the game.

If you find out that it happens to be a different mod interfering with your mod I would love to know! I apologize for my lack of knowledge and inability to help, but please do inform me if you figure out anything useful! 

Thank you so much for understanding, here is the profile code

01912213-de3e-186d-131f-830c179a06a9

Edit - 12 minutes after I posted this I realized I forgot to mention I'm playing on version 50 of the game! the VR mod hasn't updated yet so I had to play on an older version.
In order to change versions you must open lethal company on steam, press the gear icon located on the right side of the screen, select properties... at the bottom, open Betas on the popup menu's left side, and under the beta participation drop-down menu, select  previous - The previous version.

**Comment by TheAnsuz** [comment]
Thanks for all the info @Donut-man1. Let me clarify some stuff.

I am both the developer of ConfigurableCompany and LethalCompanyVariables. ConfigurableCompany is an API (it adds the menu where you can change configs and stuff) and LethalCompanyVariables is an "example mod" of what can be achieved with this mod. However you can use this github page for issues regarding any of those mods or if you want you can also contact me directly on discord.

Also don't feel bad for not understanding how something might work, you actually did a very good job locating the issue!

So, to clarify, LCV has now been updated for the latest version of Lethal Company and thus, v50 is not compatible with the latest version of the game. You should go back to a previous version of Lethal Company Variables.

_In this case, the issue you are experiencing is caused because the latest version of the game modifies a lot of stuff that needed to be implemented in LCV for it to work, rendering older versions of the game incompatible_

You should not need to also install an older version of Configurable Company as this mod should be compatible even with the first version of the game. For Lethal Company Variables version [2.3.2](https://thunderstore.io/c/lethal-company/p/AMRV/LethalCompanyVariables/versions/) should work fine.

Let me know if you have any other issue, as for the VR compatibility, it should be fixed by going back to the mentioned version.

**Comment by Donut-man1** [comment]
Thank you so much @TheAnsuz ! 

I apologize for not realizing this may be a cause, i hadn't even thought that it may not work with a different version of the game! Yes, this has fixed the terminal issue.

Thank you so much for having such a patient and kind attitude while helping me with this issue, it really does mean a lot. I can now enjoy being able to play a harder lethal company while not having to worry too much about resetting and having to work back up to where I was.

Have an amazing day!

**Comment by TheAnsuz** [comment]
No worries, glad to help!

Have fun!
