### ISSUE TITLE
[BUG] missing the mod's menu

### ISSUE THREAD

**Issue by Grzmichuj69** [TheAnsuz/Lethal-Company-Configurable-Company-API#49]
## **Describe the bug**
The mod's menu doesn't show up as it should = it's blank
## **How to reproduce the issue**
Just download the mod and enter the game
## **Mods and profile**
- Game version: v56
- Configurable company: v3.4.0

Profile code: 01911e4a-e015-fc4a-8928-dc51ca415769
![image](https://github.com/user-attachments/assets/fec1e8b1-6d29-49b1-b6af-5f8b55750bb2)

**Comment by TheAnsuz** [comment]
Hello @Grzmichuj69 

Make sure you also have [Lethal Company Variables](https://thunderstore.io/c/lethal-company/p/AMRV/LethalCompanyVariables/) installed as this mod itself is the API for that mod alongside any other mod that uses this mod to work.

Let me know if you are still experiencing this issue.
