### ISSUE TITLE
[BUG] enemy, capacity, and player values not working

### ISSUE THREAD

**Issue by Companyassit** [TheAnsuz/Lethal-Company-Configurable-Company-API#5]
I restarted Lethal Company in hopes that it would fix this issue but it did nothing but make the enemy spawn button also stop working. capacity and player values did not work either when I started up the game and as stated before, enemy spawn values do not work either in an attempt to fix this quickly. I have some mods but they are either suits, player cosmetics, and some client-sided mods too nothing that would affect the mod itself. Is there any way to fix this or is this a bug that needs to be patched?

**Comment by TheAnsuz** [comment]
Hi @Companyassit 

Do you mind sharing your profile code to check what could be the issue?

**Comment by TheAnsuz** [comment]
I see some traffic regarding this issue.

For anyone that has a similar issue. Keep in mind Lethal Company Variables does not fully support v50 (only partial support) thus some configurations may not work.

Make sure you also have the latest version for both Configurable Company and Lethal Company Variables.

If the issue persists, you can add a comment to this issue thread.
