### ISSUE TITLE
[BUG] - LethalCompanyVariables mod PlayerHealth metrics do NOT change client's health, only the hosts.

### ISSUE THREAD

**Issue by LikeableContent** [TheAnsuz/Lethal-Company-Configurable-Company-API#50]
## **Describe the bug**
For this mod in particular, any of the PlayerStats metrics (in the tab) that hosts can edit upon loading a save file does not function properly. In other words, the client's health and "defense" that is by default set to 0& defense and 100 HP are editable but do not apply to clients as they do hosts.

## **How to reproduce the issue**
You can get online or LAN with another player and edit the host's health, defense, or the other metrics such as JumpForce, SprintDuration, and MovementSpeed (before starting the save file of course) and they will only apply to the host.

## **Mods and profile**
- Game version: v56
- Configurable company: v3.4.0
- LethalCompanyVariables: v2.4.1

Profile code: 01912be5-0929-08c3-04fe-5955f60eca47

## **Extra information**
The code listed above has 3 profiles that I messed around with mainly changing the attributes of scrap (value and multiplier), interior size multiplier (which works like 98%), enemy power, and enemy capacity.

**Comment by TheAnsuz** [comment]
Hello @LikeableContent 

I might have not understood correctly, does changing the player stats not change the stats at all or does it only change them for the host?.

Thank you in advance

**Comment by LikeableContent** [comment]
Thank you for the response, changing the player stats only works for the host and not clients.

**Comment by TheAnsuz** [comment]
Thanks for the info @LikeableContent 

I assume your friends are also using the mod Lethal Company Variables, is that right?

**Comment by LikeableContent** [comment]
No, it is just me. Now that you mention it, I might not even be using it properly lol. I'm talking about making a vanilla-based server that's public. I never actually tested or played with people with LCV, which may not be an intended feature, and if so I would apologize since it's not considered a bug, good to know. I probably should've put that note in the original report.

**Comment by TheAnsuz** [comment]
No worries @LikeableContent 

Just for clarification, there are some settings that say `Synchronize with client`, that means that the value will be shared among all players in the game, so if other players don't have the mod they will have some issues.

Also, not every configuration requires synchronization, but those that require is just a limitation of the game and there is not much I can do. So for public servers sadly you are limited to those configs that don't require synchronization (some of them might work but may produce visual issues).

Hope this helps! If you are still having any other issue feel free to reopen the thread or create a new one!
