### ISSUE TITLE
[BUG] Insanely long load times as of 2.5.1

### ISSUE THREAD

**Issue by nikkidarkmatter** [TheAnsuz/Lethal-Company-Configurable-Company-API#52]
## **Describe the bug**
Before Version 2.5.1 of LCV, the game took about 10-15 seconds to launch after the fake console splash screen. As of Version 2.5.1 of LCV, the game now takes a little over 7 minutes to load after the splash screen. This issue is fixed when LCV is uninstalled and the profile is otherwise identical.

## **How to reproduce the issue**
Using the provided code, attempt to launch the game and wait until the splash screen to time the difference in launch time between Version 2.4.1 and Version 2.5.1.

## **Mods and profile**
- Game version: v56
- ConfigurableCompany: v3.5.0
- LethalCompanyVariables: v2.5.1

Profile code: 01915854-039a-4d62-4868-38851a01a05a

## **Extra information**
Attached videos and logs for example boot times for version 2.4.1 and version 2.5.1. Also overlayed in the videos is Task Manager and information provided by MSI Afterburner / RivaTuner Statistics Server, although the in-game statistics are not super helpful due to the game freezing during the load time, thus preventing the actual on-screen statistics from updating in realtime. An interesting note is that, as of 2.5.1, the RAM usage of Lethal Company appears to reset at the beginning of the load time, although the overall computer RAM usage does not drop accordingly. The videos attached demonstrate this. Overall usage between the two versions appears similar with 2.5.1 being unsurprisingly a bit higher, presumably due to the new content. Files zipped due to Github not supporting .mkv filetype.

[LCV-241-Video-and-Log.zip](https://github.com/user-attachments/files/16631128/LCV-241-Video-and-Log.zip)
[LCV-251-Video-and-Log.zip](https://github.com/user-attachments/files/16631130/LCV-251-Video-and-Log.zip)

**Comment by TheAnsuz** [comment]
Hello @nyctodarkmatter 

This issue has been resolved with the release of `3.6.0`

If you are experiencing another issue feel free to reopen or create a new issue.

Thanks in advance!
