### ISSUE TITLE
[BUG] NO MONSTERS SPAWNING ON GORDION

### ISSUE THREAD

**Issue by ScottAust1n** [TheAnsuz/Lethal-Company-Configurable-Company-API#54]
## **Describe the bug**
No monsters are spawning on Gordion despite my settings overriding it

## **How to reproduce the issue**
I maxxed everything out to see if it would work

## **Mods and profile**
It's very important that you write the version of the game and the version of Configurable Company or any related mods to the issue. Use the following line:
- Game version: v62
- Configurable company: v3.3.0

Profile code:  01917740-4d96-bc9b-4718-35efe

## **Extra information**
I want to make monsters spawn on gordion please help me fix it
![xczzcxcxcx](https://github.com/user-attachments/assets/cc105da9-80fa-4e77-9c61-59fa626f987c)

**Comment by TheAnsuz** [comment]
Hello @ScottAust1n 

I think you might have confused what those configurations actually do. They in fact increase the spawn of enemies in the level, however, they do not modify vanilla behavior (this is to keep the mod vanilla-compatible) meaning that as GORDION does not have an interior nor does it have any vents in the level, there is no way for the enemies to spawn or the logic to apply.

These settings would work if you add mods that make enemies spawn in said level, sorry if it got you confused!

Thanks in advance!
