### ISSUE TITLE
[FEATURE] global and planet settings for just 2 handed items?

### ISSUE THREAD

**Issue by Kmanqt11** [TheAnsuz/Lethal-Company-Configurable-Company-API#55]
i want to make changes to 2 handed items and small items without having to go thru each and every item

**Comment by TheAnsuz** [comment]
Hello @Kmanqt11

If you refeer to a way to differenciate them then it can be implemented in a future release, otherwise I would like to know what you mean or any way you would like this feature to be implemented.

Thanks in advance!

**Comment by TheAnsuz** [comment]
An update on the request.

I have added information in the tooltip about items being one handed or two handed. You can see this change with the upcoming release of LCV (2.6.0) wich will come in the next days.

Thanks for the report! If you however want this implementation to be different feel free to reopen the issue with an update on the suggestion.
