### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Kmanqt11** [TheAnsuz/Lethal-Company-Configurable-Company-API#56]
v2.5.2

global settings seem to work while planetary settings mostly don't. changing the scrap value of just embrion only affects the apparatus, cant stop certain monsters from spawning like the earth leviathan, stuff like that. 

I tried removing all other mods, didnt change anything. 

i really want this to work so if u can suggest i try anything

**Comment by TheAnsuz** [comment]
Hello @Kmanqt11 

Right now im on vacation but this seems to be a weird issue, can you see if the console says anything?

Also I would appreciate both the profile code and configuration settings and any other info you might find useful for the issue.

Thanks!

**Comment by TheAnsuz** [comment]
Hello @Kmanqt11 

This issue has been solved for the latest version of LCV (2.6.0) wich will be released in the next days.

Thanks for the report!
