### ISSUE TITLE
[BUG] Route Price not working

### ISSUE THREAD

**Issue by Cooljs2002** [TheAnsuz/Lethal-Company-Configurable-Company-API#60]
Describe the bug:

Setting a route price to anything other than the default does not work. It will say the price is updated but when you try to buy it, it wont let you.

How to reproduce the issue:

Just change the route price for a moon.

Mods and profile:

Only Client sided mods
Game version: v62
Profile code: 0191b239-de51-8159-4b5c-a044d682b539

Extra information:

This happens for any moon.

**Comment by TheAnsuz** [comment]
Hello @Cooljs2002 

Thanks for the report, this issue will is fixed with the 2.6.0 version wich will come in the following days.
