### ISSUE TITLE
[FEATURE]  Moon Risk Levels

### ISSUE THREAD

**Issue by Toimis** [TheAnsuz/Lethal-Company-Configurable-Company-API#64]
## **Feature**
A way to change risk/hazard levels of moons.

## **Reason**
It allows for nice flavor control since I like adjusting the difficulty and reward of certain moons (e.g. Experimentation and Embrion to make it worthwhile to explore).

## **Alternatives**
If you think it would be easy: an automated risk calculator (boolean option) based on enemy spawn power and map hazards (per day, since it may change with eclipsed/other mods/etc.), probably with higher weight toward enemy power.

**Comment by TheAnsuz** [comment]
Hello @Toimis 

The implementation itself shouldn't hard, however this mod is focused on letting the users change everything to fit their needs, I try to reserve "automatic" calculations and stuff to make it easier for players to configure the game so, while this can be implemented I don't think it reflects the current behavior of LCV.

I can add a configuration so you can feel free to update it so it shows your own value. Let me know if you want it to be implemented as that or if you have any other idea that could better fit the mod.

Thanks for the suggestion!

**Comment by TheAnsuz** [comment]
Hello back @Toimis 

I have decided to add an option to configure the hazard/risk level with configuration, you can expect this change to come with the next version of LCV (2.6.0) wich will come in the next days.

If you want this feature added in other way, feel free to reopen the issue with updated information about the feature. Thanks in advance!
