### ISSUE TITLE
[BUG] The price of the moons does not change

### ISSUE THREAD

**Issue by electricwarhorse** [TheAnsuz/Lethal-Company-Configurable-Company-API#66]
## **Describe the bug**
The price of moons doesn't change. In the menu you can try to modify the price of many items and once you're playing you'll be able to see these changes in-game. However, when you're the "host" of the game and you try to change the price of Titan or any other higher tier moon through the dropdown menu (which in the vanilla game requires a very high amount of money to travel to) then in-game this change is not seen, the game keeps asking for the same amount of money to travel to said moon regardless of the changes you may have implemented in the dropdown menu offered by the LethalVariables mod. It's as if the mod doesn't let you change the price of moons, or at least, these changes you can make in the dropdown menu are not noticeable in-game.

## **How to reproduce the issue**
Launching the modded game via Thunderstore. I usually use more mods than the ones included in the “LethalCompanyVariables” package, but this time I have disabled them to check that they do not interfere with the LethalCompanyVariables package. So, right now I am launching the game with the following mods:
BepInExPack v5.4.2100 by BepInEx
LethalCompanyVariables v2.5.2 by AMRV
ConfigurableCompany v3.5.0 by AMRV
Once we have launched the game via Thunderstore, in the main menu, we click on “Host” to host a game. In the upper left corner appears the menu that the mod provides us, the menu where we can configure the game variables.
Now we must click on “Planets” and try to change the price of Titan (for example). In the “Route price override” option you must click on the option on the right to modify the price of the moon. We will change the price of the Titan moon to “1” remembering to check the modify option on the right.
Then we click on “save settings” and immediately after that we close the menu and start the game.
In the game, on the ship, we go to the ship's command console to set the course to Titan. In the console we type: “Moons”, then “Titan” and then we will see the following message: “The cost of the route to 8-Titan is "1". It is currently wild weather on this moon (...)”. Then, we type “confirm”. However, the game will not allow us to travel to Titan because we will get another message that will say: “You could not afford these items! Your balance is 60. The total cost of these items is 700”.
This is the error that I think I've found.

## **Mods and profile**
It's very important that you write the version of the game and the version of Configurable Company or any related mods to the issue. Use the following line:
- Game version: v64 (The latest update)
- BepInExPack v5.4.2100 by BepInEx
- LethalCompanyVariables v2.5.2 by AMRV
- ConfigurableCompany v3.5.0 by AMRV
As I said before, we ussually play with more mods, but in order to prevent these from interfering with the LethalCompanyVariables mod pack I have disabled them from Thunderstore and launched the game with only those three mods I provided previously. The error persists anyway.
Profile code: Default

## **Extra information**
![LethalCompany1](https://github.com/user-attachments/assets/9536dfcb-4898-490e-bf42-f926e9630435)
![LethalCompany2](https://github.com/user-attachments/assets/8b8891ab-8e11-47b7-b33e-23360013ffa0)

**Comment by electricwarhorse** [comment]
Hey! Sorry I didn't provide the profile code earlier. Here it is: 0191c732-42e8-62ed-6a7c-4b65f4eaf672 
Thank you for your attention and your work. Sorry for the inconvenience. Best regards.

**Comment by TheAnsuz** [comment]
Hello @electricwarhorse 

Thanks for reporting this issue, Im looking at it right now and will be fixed with the next LCV update!

Also I appreciate all the information you provided, it made it easier to locate the issue!

**Comment by TheAnsuz** [comment]
Hello again.

I just wanted to confirm, this issue is fixed with LCV 2.6.0 which will be released in the next few days.

Have fun!
