### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lucasithink** [TheAnsuz/Lethal-Company-Configurable-Company-API#67]
## **Describe the bug**
so everything work normally but when in game the price of all scraps are boosted to like 100 for a bolt of example i havent touched the price increase or anything i even tried to make a new mod pack and presets for the mod and nothing seems to make it go back to normal but i think i have narrowed down the issue to variables mod which i think the latest update broke it im not sure but it only stopped working when i was testing mods today  

## **How to reproduce the issue**
just add Configurable company: v3.3.0 lethal company variables: v2.6.1 and bepinex 5.4.2100 and play the game and look for scrap 

- Game version: v49
- Configurable company: v3.3.0
- lethal company variables: v2.6.1

Profile code: 0191efbe-ea18-c610-f807-f78a3d6c4366

## **Extra information**
![1966720_254](https://github.com/user-attachments/assets/33223f6c-c7c4-4daa-a2bf-ac7a3a52fff1)

**Comment by TheAnsuz** [comment]
Hello @lucasithink 

This issue will be fixed in the next hour with the next release.

Thanks for the report!

**Comment by TheAnsuz** [comment]
The latest version of the mod has been pushed with the fix, it is `2.6.2` version of the mod.

If you have any other issues let me know!
