### ISSUE TITLE
[BUG] InvalidProgramException / Conflict with another mod

### ISSUE THREAD

**Issue by SheriffSans** [TheAnsuz/Lethal-Company-Configurable-Company-API#68]
After the 3.5.0 update, the Mirage mod refuses to work with this mod, although everything worked before that. If you remove the Configurable company, then Mirage works fine.
![1](https://github.com/user-attachments/assets/d685dc04-40d5-4760-896b-8f5128c69db2)

- Game version: v64
- Configurable company: v3.5.0

**Comment by TheAnsuz** [comment]
Hello @SheriffSans 

Although this issue happens with ConfigurableCompany installed, seems an issue on how mirage patches that method, I'd suggest contacting the mod author to check whenever they can debug the method patch.

If you want, you can also refeer them to this issue so we can further discuss the reason behind the issue.

Thanks in advance.

**Comment by qwbarch** [comment]
I'll be removing that patch in the next update, so it shouldn't be a problem anymore

**Comment by TheAnsuz** [comment]
Hello @qwbarch 

Thanks for the information! Do you mind sharing what was the reason behind the error? Maybe there was something odd in that patch or conflicting.

Thanks in advance

**Comment by qwbarch** [comment]
Well I'm just assuming for whatever reason my ``HUDManager.ApplyPenalty`` patch is somehow conflicting. That patch of mine is for a very old feature that I no longer support anyways, so removing it should fix it

**Comment by TheAnsuz** [comment]
Thank for the clarification @qwbarch 

Is there an approximate date on when the version without that patch might come? Just as a notification for anyone having this issue.

Thanks for your time!

**Comment by qwbarch** [comment]
Most likely sometime this week, I'm a bit busy right now so I'm not entirely sure when I'll get to it

**Comment by qwbarch** [comment]
Sorry ended up working on a rewrite of the mod. Update is released now so it shouldn't be an issue anymore

**Comment by TheAnsuz** [comment]
Thanks @qwbarch for the update and notification.

@SheriffSans I no longer have issues with the mod, do you mind checking if this also true for you?

Thanks in advance!
