### ISSUE TITLE
Where menu???

### ISSUE THREAD

**Issue by HexplosiveBomb** [TheAnsuz/Lethal-Company-Configurable-Company-API#7]
I cant find the menu to config

**Comment by TheAnsuz** [comment]
Hi hex, the menu will appear after clicking "host" at the top left of the screen, It's done this way as it allows you to have different settings for each save.

If you still find no menu, make sure to have LethalCompanyVariables or any other mod that implements configurations

**Comment by TheAnsuz** [comment]
Hey @HexplosiveBomb 

I will be closing the issue as I have no information regarding the question. If you are still unable to open the menu or can't find it, you can open back the issue and I will gladly help you with the problem.
