### ISSUE TITLE
[BUG] Synchronization Settings Issue

### ISSUE THREAD

**Issue by squiggly333** [TheAnsuz/Lethal-Company-Configurable-Company-API#71]
## **Describe the bug**
Shop and Moon prices do not sync with other players in the lobby. Same with changed player stats like stamina and speed. All these changes appear on my client as the host and work as intended there, but not on the other players. Every player has the mod installed. 

## **How to reproduce the issue**
Changed settings that require synchronization. I host the lobby and invite other players that all have Lethal Company Variables installed. I check the shop prices and they are accurate for me, the host, and inaccurate for other players. This remains true for player stats. 

## **Mods and profile**
- Game version: v64
- Configurable company: v3.6.0

Profile code: 01925167-6279-32b5-3d2f-b8b81b05205d

## **Extra information**
[Friend_LogOutput.log](https://github.com/user-attachments/files/17241146/Friend_LogOutput.log)
[Host_LogOutput.log](https://github.com/user-attachments/files/17241154/Host_LogOutput.log)

**Comment by TheAnsuz** [comment]
Hello @squiggly333 

Do you mind sending a console log from host and friend where both enter the game? The logs you sent seem to have some missing information.

Thanks in advance

**Comment by TheAnsuz** [comment]
Hello @squiggly333 

With the latest update of configurable company you shouldn't have any issues, can you confirm this is the case?

Thanks in advance!

**Comment by squiggly333** [comment]
Yeah it looks like its fixed now! Stats remain synced and the prices for moons and items are the same across all players. Haven't gotten to test scaling map size but I imagine that should be fine if the others are synced. Thanks!

**Comment by TheAnsuz** [comment]
Glad to hear that!

Let me know if you encounter any other problems. I will be closing the issue but feel free to reopen it anytime!

Enjoy the mod!
