### ISSUE TITLE
[BUG] Some items get double the value

### ISSUE THREAD

**Issue by TRAPGamer07** [TheAnsuz/Lethal-Company-Configurable-Company-API#72]
## **Describe the bug**
Some items like apparatus, keys and hives have double the normal value (app=160, key=6)

## **Mods and profile**
just using this mod

- Game version: v64
- Configurable company: v3.6.0

Profile code: 0192726e-28f8-a2a0-3347-cea9b1cb311b

## **Extra information**
I did not configure anything besides factory size multiplier

**Comment by TheAnsuz** [comment]
Hello @TRAPGamer07 

This issue will be fixed with 2.7.0, this version will be released later this week.

Thanks for the report!
