### ISSUE TITLE
[BUG] Time scale slider non-functional after v65 update.

### ISSUE THREAD

**Issue by DravenXD** [TheAnsuz/Lethal-Company-Configurable-Company-API#73]
## **Describe the bug**
Using the [Time Speed] slider does not adjust time scale in game after v65. (tested on modded moon: Halation by DemonMae with liminal pools interior by theMenagerie).

## **How to reproduce the issue**
-

## **Mods and profile**
- Game version: v65
- Configurable company: v3.6.0

Profile code: 0192bad3-0a05-8352-5db2-b3822efac1ff

## **Extra information**
-

**Comment by TheAnsuz** [comment]
Hello @DravenXD 

Lethal company variables has not been updated to v65 yet, it will take a few days.

Issue should be solved after the next update.

Thanks in advance!

**Comment by TheAnsuz** [comment]
Hello again @DravenXD 

As LCV updated yesterday, I will be closing this issue.

If you have any problems after the update, feel free to reopen the issue with updated information.

Thanks in advance
