### ISSUE TITLE
[BUG] Nothing shows when opening the menu

### ISSUE THREAD

**Issue by LeafiDev** [TheAnsuz/Lethal-Company-Configurable-Company-API#8]
## **Describe the bug**
I opened the menu when on file 2 that hasn't been created yet. there were no options

## **How to reproduce the issue**
Opening the menu on file 2?

## **Expected behavior**
A menu that actually can be seen

## **Mods**
Only mods needed for this one

## **Extra information**
There's also some weird text on the side
![Screenshot 2024-04-06 102147](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/83046401/64f0c849-2e33-4dd5-b2b0-353744bca5e9)

**Comment by TheAnsuz** [comment]
Hello @SillyCubeGuy 

I'll be looking into the issue, could you provide your profile code?

Thanks in advance.

**Comment by LeafiDev** [comment]
018eb3d8-f646-ac45-5dd7-d572b358891d

**Comment by TheAnsuz** [comment]
Thank you.
I will inform you as soon as posible.

**Comment by TheAnsuz** [comment]
@SillyCubeGuy 

The profile code you shared has only LCV.
I am wondering, does this issue occur in v49 or v50 of the game?

**Comment by LeafiDev** [comment]
V50

**Comment by TheAnsuz** [comment]
@SillyCubeGuy 

Seems like something in the newer version made LCV incompatible. I will work in a fix but keep in mind **LCV is not planned to support the beta, v50 will be only worked on upon full release**

**Comment by LeafiDev** [comment]
Understood :>

**Comment by TheAnsuz** [comment]
Thank you @SillyCubeGuy for understanding.

I will inform about this fix in the Discord channel if you want to receive an update on the progress and updates within the v50 upgrade. (https://discord.gg/BxTXuKUS). You can find the channel by searching "Lethal company variables".

Thanks in advance for reporting this issue.
